FROM php:5-apache

RUN a2enmod rewrite
RUN apt-get update && \
    apt-get install -y libxml2 libxml2-dev && \
    docker-php-ext-install mysqli soap dom
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini
